import unittest
import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(current_dir)
parent_of_repo = os.path.dirname(repo_root)
repo_name = os.path.basename(repo_root)

sys.path.insert(0, parent_of_repo)

try:
    comfy_compat = __import__(f"{repo_name}.comfy_compat", fromlist=["io"])
    io = comfy_compat.io
except ImportError:
    sys.path.insert(0, repo_root)
    from comfy_compat import io

class TestComfyCompat(unittest.TestCase):
    def test_schema_generation(self):
        # Define a mock node using V3 schema
        class MyNode(io.ComfyNode):
            @classmethod
            def define_schema(cls):
                return io.Schema(
                    node_id="MyNode",
                    display_name="My Node",
                    category="Test",
                    inputs=[
                        io.Image.Input("image"),
                        io.Int.Input("val", default=0, min=0, max=10),
                        io.Float.Input("opt", optional=True)
                    ],
                    outputs=[io.Image.Output(), io.Int.Output("count")]
                )

            @classmethod
            def execute(cls, image, val, opt=None):
                return io.NodeOutput(image, val)

        # Check legacy attributes generated by shim
        self.assertTrue(hasattr(MyNode, "INPUT_TYPES"))
        self.assertTrue(hasattr(MyNode, "RETURN_TYPES"))
        self.assertTrue(hasattr(MyNode, "RETURN_NAMES"))
        self.assertEqual(MyNode.CATEGORY, "Test")
        self.assertEqual(MyNode.FUNCTION, "execute_wrapper")

        inputs = MyNode.INPUT_TYPES()
        self.assertIn("image", inputs["required"])
        self.assertIn("val", inputs["required"])

        # Check type definitions
        self.assertEqual(inputs["required"]["image"][0], "IMAGE")
        self.assertEqual(inputs["required"]["val"][0], "INT")

        # Check kwargs
        self.assertEqual(inputs["required"]["val"][1]["default"], 0)
        self.assertEqual(inputs["required"]["val"][1]["min"], 0)

        # Check optional
        self.assertIn("opt", inputs["optional"])
        self.assertEqual(inputs["optional"]["opt"][0], "FLOAT")

        # Check outputs
        self.assertEqual(MyNode.RETURN_TYPES, ("IMAGE", "INT"))
        self.assertEqual(MyNode.RETURN_NAMES, (None, "count"))

if __name__ == "__main__":
    unittest.main()
